/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2018-01-18 01:02:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.content.or;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class qrcode4XSBatchUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<title>二维码");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("的值</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statics/css/bootstrap.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/bootstrap.min.js\"></script>\r\n");
      out.write("<button onclick=\"back()\">返回</button>\r\n");
      out.write("<br>\r\n");
      out.write("<input id=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" type=\"text\" name=\"id\">\r\n");
      out.write("<button onclick=\"query()\">ID查询</button>\r\n");
      out.write("<br>\r\n");
      out.write("<input id=\"qrcode\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.qrcode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" type=\"text\" size=\"10\" maxlength=\"10\" name=\"qrcode\">\r\n");
      out.write("<button onclick=\"queryByCode()\">Code查询</button>\r\n");
      out.write("<hr>\r\n");
      out.write("<div id=\"One\"></div>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/handlebars.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/common.js\"></script>\r\n");
      out.write("<script id=\"one-template\" type=\"text/x-handlebars-template\">\r\n");
      out.write("<div>msg:{{msg}}  code:{{code}}</div>\r\n");
      out.write("<form role=\"form\" action=\"javascript:void(0)\" method=\"post\">\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t\t<div class=\"col-xs-12 column\">\r\n");
      out.write("\t\t\t<label for=\"id\">id</label>\r\n");
      out.write("\t\t\t<input id=\"id\" name=\"id\" value=\"{{result.id}}\" type=\"text\" required=\"required\" class=\"form-control\" readonly=\"readonly\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t\t<div class=\"col-xs-6 column\">\r\n");
      out.write("\t\t\t<label for=\"url\">url</label>\r\n");
      out.write("\t\t\t<input id=\"url\" name=\"url\" value=\"{{result.url}}\" type=\"text\" required=\"required\" class=\"form-control\" readonly=\"readonly\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-xs-6 column\">\r\n");
      out.write("\t\t\t<label for=\"prefix\">prefix</label>\r\n");
      out.write("\t\t\t<input id=\"prefix\" name=\"prefix\" value=\"{{result.prefix}}\" type=\"text\" required=\"required\" class=\"form-control\" readonly=\"readonly\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t\t<div class=\"col-xs-3 column\">\r\n");
      out.write("\t\t\t<label for=\"en\">en</label>\r\n");
      out.write("\t\t\t<input id=\"en\" name=\"en\" value=\"{{result.en}}\"  type=\"text\" required=\"required\" class=\"form-control\" readonly=\"readonly\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-xs-3 column\">\r\n");
      out.write("\t\t\t<label for=\"bn\">bn</label>\r\n");
      out.write("\t\t\t<input id=\"bn\" name=\"bn\" value=\"{{result.bn}}\" type=\"text\" required=\"required\" class=\"form-control\" readonly=\"readonly\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-xs-3 column\">\r\n");
      out.write("\t\t\t<label for=\"num\">num</label>\r\n");
      out.write("\t\t\t<input id=\"num\" name=\"num\" value=\"{{result.num}}\" type=\"text\" required=\"required\" class=\"form-control\" readonly=\"readonly\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-xs-3 column\">\r\n");
      out.write("\t\t\t<label for=\"code\">code</label>\r\n");
      out.write("\t\t\t<input id=\"code\" name=\"code\" value=\"{{result.code}}\" type=\"text\" required=\"required\" class=\"form-control\" readonly=\"readonly\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("    <button type=\"button\" class=\"btn btn-primary\" onclick=\"deleteById('{{result.id}}')\">删除</button>\r\n");
      out.write("    <button type=\"button\" class=\"btn btn-primary\">激活</button>\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-primary\">批量激活</button>\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-primary\">反激活</button>\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-primary\">生效</button>\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-primary\">失效</button>\r\n");
      out.write("\t{{#batchId_eq result.batchId -1}}{{/batchId_eq}}\r\n");
      out.write("</form>\r\n");
      out.write("<div>BatchId:{{result.batchId}}</div>\r\n");
      out.write("<div>CreateTime:{{result.createTime}}</div>\r\n");
      out.write("<div>ActivaeStatus:{{result.activateStatus}}</div>\r\n");
      out.write("<div>Status:{{result.status}}</div>\r\n");
      out.write("</script>\r\n");
      out.write("<script id=\"batch-template\" type=\"text/x-handlebars-template\">\r\n");
      out.write("<div>msg:{{msg}}  code:{{code}}</div>\r\n");
      out.write("{{#each content}}\r\n");
      out.write("<form role=\"form\" action=\"javascript:void(0)\" method=\"post\">\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t\t<div class=\"col-xs-12 column\">\r\n");
      out.write("\t\t\t<label for=\"id\">id</label>\r\n");
      out.write("\t\t\t<input id=\"id\" name=\"id\" value=\"{{id}}\" type=\"text\" required=\"required\" class=\"form-control\" readonly=\"readonly\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t\t<div class=\"col-xs-3 column\">\r\n");
      out.write("\t\t\t<label for=\"en\">en</label>\r\n");
      out.write("\t\t\t<input id=\"en\" name=\"en\" value=\"{{en}}\"  type=\"text\" required=\"required\" class=\"form-control\" readonly=\"readonly\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-xs-3 column\">\r\n");
      out.write("\t\t\t<label for=\"bn\">bn</label>\r\n");
      out.write("\t\t\t<input id=\"bn\" name=\"bn\" value=\"{{bn}}\" type=\"text\" required=\"required\" class=\"form-control\" readonly=\"readonly\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-xs-3 column\">\r\n");
      out.write("\t\t\t<label for=\"num\">num</label>\r\n");
      out.write("\t\t\t<input id=\"num\" name=\"num\" value=\"{{num}}\" type=\"text\" required=\"required\" class=\"form-control\" readonly=\"readonly\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-xs-3 column\">\r\n");
      out.write("\t\t\t<label for=\"code\">code</label>\r\n");
      out.write("\t\t\t<input id=\"code\" name=\"code\" value=\"{{code}}\" type=\"text\" required=\"required\" class=\"form-control\" readonly=\"readonly\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("    <button type=\"button\" class=\"btn btn-primary\" onclick=\"deleteById('{{id}}')\">删除</button>\r\n");
      out.write("    <button type=\"button\" class=\"btn btn-primary\">激活</button>\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-primary\">批量激活</button>\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-primary\">反激活</button>\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-primary\">生效</button>\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-primary\">失效</button>\r\n");
      out.write("\t{{#batchId_eq batchId -1}}{{/batchId_eq}}\r\n");
      out.write("</form>\r\n");
      out.write("<div>BatchId:{{batchId}}</div>\r\n");
      out.write("<div>CreateTime:{{createTime}}</div>\r\n");
      out.write("<div>ActivaeStatus:{{activateStatus}}</div>\r\n");
      out.write("<div>Status:{{status}}</div>\r\n");
      out.write("{{/each}}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("Handlebars.registerHelper('batchId_eq', function(v1, v2) {\r\n");
      out.write("    if(v1 === v2)\r\n");
      out.write("    \treturn \"<button type=\\\"button\\\" class=\\\"btn btn-primary\\\">绑定批号</button>\";\r\n");
      out.write("    else\r\n");
      out.write("    \treturn \"<button type=\\\"button\\\" class=\\\"btn btn-primary\\\">批次信息</button>\";\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\tquery();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function StringBuffer() {\r\n");
      out.write("    this.__strings__ = new Array();\r\n");
      out.write("}\r\n");
      out.write("StringBuffer.prototype.append = function (str) {\r\n");
      out.write("    this.__strings__.push(str);\r\n");
      out.write("    return this;    //方便链式操作\r\n");
      out.write("}\r\n");
      out.write("StringBuffer.prototype.toString = function () {\r\n");
      out.write("    return this.__strings__.join(\"\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function query(){\r\n");
      out.write("\tget($(\"#id\").val());\r\n");
      out.write("}\r\n");
      out.write("function queryByCode(){\r\n");
      out.write("\tvar code = $(\"#qrcode\").val();\r\n");
      out.write("\tvar en=code.substr(0,2);\r\n");
      out.write("\tvar bn=code.substr(2,2);\r\n");
      out.write("\tvar num=\"\"+code.substr(4,6);\r\n");
      out.write("\t$.getJSON(config.serverIp+\"or/qr/findByEnBnNum\",{\"en\":en,\"bn\":bn,\"num\":num},function(data){\r\n");
      out.write("\t\tmsg = $.parseJSON(data);\r\n");
      out.write("\t\tif( msg.code==\"0\"&& msg.msg==\"OK\"){\r\n");
      out.write("            render_modal(\"#batch-template\",msg,\"#One\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tconsole.log(msg.msg);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("function back(){\r\n");
      out.write("\twindow.history.go(-1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function deleteById(id){\r\n");
      out.write("\tif(window.confirm('你确定要删除该记录吗？')){\r\n");
      out.write("\t\t$.getJSON(config.serverIp+\"or/qr/delById\",{\"id\":id},function(data){\r\n");
      out.write("\t\t\tif(data != null){\r\n");
      out.write("\t\t\t\tmsg = $.parseJSON(data);\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\talert(\"数据为空！\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif( msg.code===\"0\"&& msg.msg===\"OK\"){\r\n");
      out.write("\t\t\t\talert(msg.msg);\r\n");
      out.write("\t\t\t\tback();\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\talert(msg.msg);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("        return true;\r\n");
      out.write("     }else{\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function get(id){\r\n");
      out.write("\t$.getJSON(config.serverIp+\"or/qr/findById\",{\"id\":id},function(data){\r\n");
      out.write("\t\tif(data != null){\r\n");
      out.write("\t\t\tmsg = $.parseJSON(data);\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\talert(\"数据为空！\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif( msg.code==\"0\"&& msg.msg==\"OK\"){\r\n");
      out.write("            render_modal(\"#one-template\",msg,\"#One\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tconsole.log(msg.msg);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
