/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2018-01-18 01:02:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.content;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_005for_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" <meta charset=\"utf-8\">\r\n");
      out.write(" <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write(" <meta content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\" name=\"viewport\">\r\n");
      out.write(" <title>溯源系统</title>\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statics/css/bootstrap.min.css\">\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statics/css/font-awesome.min.css\">\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statics/css/AdminLTE.min.css\">\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statics/css/all-skins.min.css\">\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statics/css/main.css\">\r\n");
      out.write(" <style>\r\n");
      out.write(" #rrapp .content-wrapper .content{background:#fff;}\r\n");
      out.write(" #rrapp .content-wrapper .content iframe{width:100%;min-height:1000px;overflow:visible;background:#fff;border:0;}\r\n");
      out.write(" .show_index{font-size:20px;position:relative;top:2px;left:-3px;}\r\n");
      out.write(" .treeview-menu{display:none;}\r\n");
      out.write(" </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"hold-transition skin-blue sidebar-mini\">\r\n");
      out.write("<div class=\"wrapper\" id=\"rrapp\">\r\n");
      out.write("  <header class=\"main-header\">\r\n");
      out.write("    <a href=\"javascript:void(0);\" class=\"logo\">\r\n");
      out.write("      <span class=\"logo-mini\"><b>&nbsp;&nbsp;</b></span>\r\n");
      out.write("      <span class=\"logo-lg\"><b>溯源系统</b></span>\r\n");
      out.write("    </a>\r\n");
      out.write("    <nav class=\"navbar navbar-static-top\" role=\"navigation\">\r\n");
      out.write("      <a href=\"#\" class=\"sidebar-toggle\" data-toggle=\"offcanvas\" role=\"button\">\r\n");
      out.write("        <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("      </a>\r\n");
      out.write("\t  <div style=\"float:left;color:#fff;padding:15px 10px;\">欢迎<!--  {{user.username}} -->用户名</div>\r\n");
      out.write("      <div class=\"navbar-custom-menu\">\r\n");
      out.write("        <ul class=\"nav navbar-nav\">\r\n");
      out.write("          <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index_or\" target=\"_top\"><i class=\"fa fa-home\"></i> &nbsp;首页</a></li>\r\n");
      out.write("\t\t  <li><a href=\"javascript:void(0);\" data-toggle=\"modal\" data-target=\"#update_password\"><i class=\"fa fa-lock\"></i> &nbsp;修改密码</a></li>\r\n");
      out.write("          <li><a href=\"javascript:exit('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\"><i class=\"fa fa-sign-out\"></i> &nbsp;退出系统</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("  </header>\r\n");
      out.write("  <aside class=\"main-sidebar\">\r\n");
      out.write("    <div class=\"sidebar\">\r\n");
      out.write("      <ul class=\"sidebar-menu\">\r\n");
      out.write("        <li class=\"header\">导航菜单</li>\r\n");
      out.write("\t\t<li class=\"add\">\r\n");
      out.write("\t\t\t<a href=\"javascript:void(0);\">\r\n");
      out.write("\t\t\t\t<i class=\"fa fa-cog\"></i>\r\n");
      out.write("\t\t\t\t<span>基础信息录入</span>\r\n");
      out.write("\t\t\t\t<i class=\"fa fa-angle-left pull-right\"></i>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<ul class=\"treeview-menu\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/or/companyAdd\" target=\"content\"><i class=\"fa fa-file-text-o\"></i>增加公司信息</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/or/batchInfoAdd\" target=\"content\"><i class=\"fa fa-file-text-o\"></i>增加批次信息</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/or/productAdd\" target=\"content\"><i class=\"fa fa-file-text-o\"></i>增加产品信息</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/or/registerOR\" target=\"content\"><i class=\"fa fa-file-text-o\"></i>公司批号关联</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/or/inspectionInfoAdd\" target=\"content\"><i class=\"fa fa-file-text-o\"></i>增加检验信息</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/or/processLogAdd\" target=\"content\"><i class=\"fa fa-file-text-o\"></i>增加过程日志</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/or/retroactiveInfoAdd\" target=\"content\"><i class=\"fa fa-file-text-o\"></i>增加追溯信息</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"index\">\r\n");
      out.write("\t\t\t<a href=\"javascript:void(0);\">\r\n");
      out.write("\t\t\t\t<i class=\"fa fa-cog\"></i>\r\n");
      out.write("\t\t\t\t<span>基础信息查询</span>\r\n");
      out.write("\t\t\t\t<i class=\"fa fa-angle-left pull-right\"></i>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<ul class=\"treeview-menu\">\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/or/companyList\" target=\"content\"><i class=\"fa fa-th-list\"></i>公司信息列表</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/or/batchInfoList\" target=\"content\"><i class=\"fa fa-th-list\"></i>批次信息列表</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/or/productList\" target=\"content\"><i class=\"fa fa-th-list\"></i>产品信息列表</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"qrcode\">\r\n");
      out.write("\t\t\t<a href=\"javascript:void(0);\">\r\n");
      out.write("\t\t\t\t<i class=\"fa fa-cog\"></i>\r\n");
      out.write("\t\t\t\t<span>溯源信息维护</span>\r\n");
      out.write("\t\t\t\t<i class=\"fa fa-angle-left pull-right\"></i>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<ul class=\"treeview-menu\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/or/qrcode4XSBatchNo\" target=\"content\"><i class=\"fa fa-th-list\"></i>二维码批次信息查询</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/or/qrcode4XSBatchUpdate\" target=\"content\"><i class=\"fa fa-th-list\"></i>批次修改作业</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/or/readFromFile2DB\" target=\"content\"><i class=\"fa fa-th-list\"></i>数据导入</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"kjfs\">\r\n");
      out.write("\t\t\t<a href=\"javascript:void(0);\">\r\n");
      out.write("\t\t\t\t<i class=\"fa fa-cog\"></i>\r\n");
      out.write("\t\t\t\t<span>快捷方式</span>\r\n");
      out.write("\t\t\t\t<i class=\"fa fa-angle-left pull-right\"></i>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<ul class=\"treeview-menu\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/oSearch\" target=\"content\"><i class=\"fa fa-th-list\"></i>夏商查询入口</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </aside>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"content-wrapper\">\r\n");
      out.write("    <section class=\"content-header\">\r\n");
      out.write("      <ol class=\"breadcrumb\" id=\"nav_title\" style=\"position:static;float:none;\">\r\n");
      out.write("        <li class=\"active\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index_or\" target=\"_top\"><i class=\"fa fa-home show_index\"></i> &nbsp; 首页</a></li>\r\n");
      out.write("        <li class=\"active\">导航</li>\r\n");
      out.write("      </ol>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section class=\"content\">\r\n");
      out.write("      <iframe name=\"content\"></iframe>\r\n");
      out.write("    </section>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <footer class=\"main-footer\">\r\n");
      out.write("    <div class=\"pull-right hidden-xs\">\r\n");
      out.write("      Version 1.0.0\r\n");
      out.write("    </div>\r\n");
      out.write("    Copyright &copy; 2017 <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" target=\"_blank\">cioclass.com</a> All Rights Reserved 洋葱头信息科技有限公司\r\n");
      out.write("  </footer>\r\n");
      out.write("  <div class=\"control-sidebar-bg\"></div>\r\n");
      out.write("  <div class=\"modal fade black in\" id=\"update_password\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"false\" style=\"display: none;\">\r\n");
      out.write("\t    <div class=\"modal-dialog\">\r\n");
      out.write("\t        <div class=\"modal-content\">\r\n");
      out.write("\t            <div class=\"modal-header\">\r\n");
      out.write("\t                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">×</button>\r\n");
      out.write("\t                <h4 class=\"modal-title\" id=\"myModalLabel2\">修改密码</h4>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <div class=\"modal-body\" id=\"content\">\r\n");
      out.write("\t\t            <form class=\"form-horizontal\">\r\n");
      out.write("\t\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t        <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t          <div class=\"col-sm-2 control-label\">账号</div>\r\n");
      out.write("\t\t\t\t            <span class=\"label label-success\">用户名</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"col-sm-2 control-label\">原密码</div>\r\n");
      out.write("\t\t\t\t\t      <div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t  <input type=\"password\" class=\"form-control\" name=\"password\" placeholder=\"原密码\"/>\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"col-sm-2 control-label\">新密码</div>\r\n");
      out.write("\t\t\t\t\t\t  \t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t      <input type=\"text\" class=\"form-control\" name=\"newPassword\" placeholder=\"新密码\"/>\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <div class=\"modal-footer\">\r\n");
      out.write("\t            \t<button type=\"button\" class=\"btn btn-primary\">修改密码</button>\r\n");
      out.write("\t                <button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\">关闭</button>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/vue.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/router.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery.slimscroll.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/fastclick.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/app.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statics/plugins/layer/layer.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/index.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function exit(path){\r\n");
      out.write("\tif(window.confirm('确认立即退出系统？')){\r\n");
      out.write("\t\tlocation.href=path+\"/logout\";\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn false;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
